### Basic url
@baseUrl = http://localhost:3000/collectibles

### Get the amount of collectibles
GET {{baseUrl}}/1

### Add collectibles
PUT {{baseUrl}}/addCollectible/1
Content-Type: application/json

{
    "collectible" : 100
}

### Get the amount of collectibles
GET {{baseUrl}}/1

### Supp collectibles
PUT {{baseUrl}}/suppCollectible/1
Content-Type: application/json

{
    "collectible" : 100
}

### Get the amount of collectibles
GET {{baseUrl}}/1