### Basic url
@baseUrl = http://localhost:3000/collectibles

### Get the amount of collectibles
GET {{baseUrl}}/1

### Get the amount of collectibles
GET {{baseUrl}}/4

### Add collectibles
PUT {{baseUrl}}/addCollectible/4
Content-Type: application/json

{
    "collectible" : 355
}

### Supp collectibles
PUT {{baseUrl}}/suppCollectible/1
Content-Type: application/json

{
    "collectible" : 100
}