### Basic url
@baseUrl = http://localhost:3000


# @name test
### Login as test user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"test",
    "password":"test"
}

### Get the amount of collectibles
GET {{baseUrl}}/collectibles
Content-Type: application/json
Authorization: {{test.response.body.token}}



{
    "collectible" : 100
}

### Add collectibles
PUT {{baseUrl}}/collectibles/addCollectible/
Content-Type: application/json
Authorization: {{test.response.body.token}}



{
    "collectible" : 100
}

### Supp collectibles
PUT {{baseUrl}}/collectibles/suppCollectible/
Content-Type: application/json
Authorization: {{test.response.body.token}}



{
    "collectible" : 900
}
