
### Basic url
@baseUrl = http://localhost:3000

### Get all scores in correct order
GET {{baseUrl}}/scores


# @name test
### Login as test user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"test",
    "password":"test"
}

### First score of test user at 20
PUT {{baseUrl}}/scores
Content-Type: application/json
Authorization: {{test.response.body.token}}



{
    "score": 20
}


### Updating the scores of test user at 1000
PUT {{baseUrl}}/scores
Content-Type: application/json
Authorization: {{test.response.body.token}}


{
    "score": 1000
}
