
### Basic url
@baseUrl = http://localhost:3000





### Get all score in order [id, score]
GET {{baseUrl}}/scores


### put socres
PUT {{baseUrl}}/scores
Content-Type: application/json

{
    "score": 125
}
