### Basic url
@baseUrl = http://localhost:3000

### Login as test user
# @name test
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"test",
    "password":"test"
}

### Get all skins in order by price
GET {{baseUrl}}/skins

### Get all skins of a player
GET {{baseUrl}}/skins/getuserskins
Content-Type: application/jsnpm on
Authorization: {{test.response.body.token}}


### Give a skin to a player
PUT {{baseUrl}}/skins/
Content-Type: application/json
Authorization: {{test.response.body.token}}

{
    "item": 5
}

### Try to give a skin that doesn't exist
PUT {{baseUrl}}/skins/
Content-Type: application/json
Authorization: {{test.response.body.token}}

{
    "item": 10000
}