### Basic url
@baseUrl = http://localhost:3000

### Login as test user
# @name test
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"test",
    "password":"test"
}

### Get all theme in order by price
GET {{baseUrl}}/themes

### Get all skins of a player
GET {{baseUrl}}/themes/getuserthemes
Content-Type: application/json
Authorization: {{test.response.body.token}}


### Give a theme to a player
PUT {{baseUrl}}/themes/
Content-Type: application/json
Authorization: {{test.response.body.token}}

{
    "item": 5
}


### Try to give a theme that doesn't exist
PUT {{baseUrl}}/themes/
Content-Type: application/json
Authorization: {{test.response.body.token}}

{
    "item": 10000
}